config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  devise_for :users 
  resources :chatroom do
    collection do
      get :users
    end
  end
  resources :messages
  root "welcome#root"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :user
validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    def after_sign_in_path_for(resource)
        chatroom_index_path(current_user) # your path
      end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
def index
    @messages = Message.all
end

def users
    @users = User.all
end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    
    def create
      @message = Message.new(message_params)
      @message.user_id = current_user.id
      if @message.save
        # ActionCable.server.broadcast("room_controller" , {body: "working"})
        redirect_to chatroom_index_path
      end
  end

    private
    def message_params
      params.require(:message).permit(:body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    # root page of Application
    def root
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/_chatbot.html.erb
<div class="ui fluid raised card chatbox">
  <div class="content" , id = "messages">
    <div class="header">Message Time</div>
    <hr>
 
<div class="ui small feed">
<% @messages.each do |m| %>  
<div class="event" >
    <div class="content">
    <% if m.user.email == current_user.email %>
    <div class="summary text_right ">
    <small >[<%= m.created_at.strftime("%H:%M") %>]</small>  - <%= m.body %>
     
    </div>
    <% else %>
      <div class="summary">
         <em><%= m.user.email %></em>: <%= m.body %> -
         <small >[<%= m.created_at.strftime("%H:%M") %>]</small>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>

</div>
</div>
        <div class="extra content">
        <div class = "ui reply form" >
                <%= form_for Message.new do |m| %>
                <div class="field input">
                <%= m.text_field :body , placeholder: "Write your message..." %>
                </div>
                <div class="ui blue labeled submit icon button">
                 <i class="edit icon"> </i>  <%= m.submit %>
                </div>
                <% end %>
                </div>
        </div>
</div>

app/views/chatroom/_online.html.erb
<div class="ui card chatbox">
  <div class="content">
<div class="ui inverted pointing vertical menu">
  <a class="item">
   Online Users
  </a>
  <div class="item">
    <b>Grouped Section</b>
    <div class="menu">
      <a class="item">Subsection 1</a>
      <a class="item">Subsection 1</a>
      <a class="item">Subsection 1</a>
    </div>
  </div>
</div>
</div>
</div>

app/views/chatroom/index.html.erb
<div class= "ui container">
<div class="ui success message shut_div">
<%= flash[:success] = "Welcome #{current_user.email}" %>
<i class="window close icon shut_icon"></i>
</div>
</div>
<h2 class="ui center aligned big icon header">
<%= image_tag "logo.png"%><br>
 Message Me
</h2>
<br><br><br>
<div class= "ui container">
<div class="ui two column grid">
<div class="twelve wide column">
   <%= render :partial => "chatbot" %>
</div>
 

<div class="four wide column">
<%= render :partial => "online" %>
</div>
</div>
</div>

<script>
$(document).ready(function(){
    $(".shut_icon").click(function(){
       $(".shut_div").hide();
    })
    
})
</script>

app/views/chatroom/users.html.erb
<br><br>
<div class= "ui container">
<table class="ui celled striped table">
  <thead>
    <tr><th colspan="3">
      Users
    </th>
  </tr></thead>
  <tbody>
  <% @users.each do |u| %>
    <tr>
      <td class="collapsing">
        <i class="user icon"></i>
      </td>
      <td><%= u.email %></td>
      <td class="right aligned collapsing"><%= u.created_at.strftime("%Y-%m-%d")%></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/layouts/_javascript.html.erb
<script>
$(document).ready(function(){
    $('.ui.dropdown').dropdown();
})
</script>

app/views/layouts/_navbar.html.erb
<div class="ui tiny inverted menu">
  <a class="item">
  <%= image_tag 'logo.png' %>
  </a>
  <% if user_signed_in? %>
 
    <%= link_to "Chatroom" , chatroom_index_path, class:"item" %>
   <%= link_to "Users" , users_chatroom_index_path , class:"item" %>
  <% end %>
  <div class="right menu">
    <div class="ui dropdown item">
      Actions <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item">Profile</a>
        <a class="item">Edit Profile</a>
        <a class="item">Change Password</a>
       
      </div>
    </div>
    <div class="item">
       <% if !user_signed_in? %> <%= button_to "Login" , new_user_session_path , class: "ui primary button" %>  <%= button_to "Register Yourself" , new_user_registration_path , class: "ui primary button" %><% else %> <%= button_to "Logout" ,  destroy_user_session_path , method: :delete , class: "ui primary button"  %> <% end %>
       
    </div>
  </div>
</div>
<%= render :partial => "layouts/javascript" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'logo.png'%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render :partial => "layouts/navbar" %>
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  
    </div>
    <%= yield %>
  </body>
</html>

app/views/welcome/root.html.erb
<h1 class="ui center aligned icon header">
  <%= image_tag "logo.png" %> <br>
  Message Me 
</h1>
<div class = "ui container">
<h4 class="ui center aligned icon header">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</h4>
</div>
<br><br><br>
<div class="ui grid">
  <div class="six wide column"> 
        <h2 class="ui center aligned icon header">
        <i class = "chart line icon"></i>
        <div class="content">
            Learn More
        </div>
        </h2> 
        <h4 class="ui center aligned icon header">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </h4>
</div>
<div class="five wide column"> 
<h2 class="ui center aligned icon header">
<i class = "plug icon"></i>
<div class="content">
    Plug-in
</div>
</h2> 
<h4 class="ui center aligned icon header">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </h4>
</div>
<div class="five wide column"> 
<h2 class="ui center aligned icon header">
<i class = "random icon"></i>
<div class="content">
   Mission
</div>
</h2> 
<h4 class="ui center aligned icon header">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </h4>
</div>
</div>